### PR TITLE
fix: layout and no editor view

### PR DESCRIPTION
**Pull request by Bikash9609**
UI to shrink when the no editor view is active. Currently, the DB layout forms downwards which should be from left to right. The proposed solution fixes it, tho not completely but to some extent.

### CODE REVIEW

**Comment by Bikash9609** [comment]
@Ovyerus

**Comment by Bikash9609** [comment]
https://github.com/Ovyerus/prismaliser/assets/50935456/bfe81767-067c-4499-8616-ea89c00c64ad

Tried making the UI much more free in terms of focus.

**Comment by Ovyerus** [comment]
Thanks for bringing the direction option to my knowledge! I've made the commit ab228c4 with only that change as I'm not fond of the header change personally.

**Comment by Bikash9609** [comment]
Np, thanks.

**Pull request closed without merging**
