### PR TITLE
Updating next package to 15.1.3 and added copyfiles in dev dependency

### PR DESCRIPTION
**Pull request by codewithshinde**
**Changes:**
upgraded next to 15.1.3

I have added **copyfiles** as a development dependency because the cp command is not supported in the Windows Command Prompt during the build process. This change ensures that our build script works seamlessly across different operating systems, including Windows.

### CODE REVIEW

**Comment by Ovyerus** [comment]
I would rather not add another dependency just for copying; if you use PowerShell (specifically the more up to date PowerShell Core, not sure about the built in Windows PowerShell), it comes with a `cp` alias and can understand the `-r` flag just fine from what I can remember, so it should work fine here.

**Comment by codewithshinde** [comment]
> I would rather not add another dependency just for copying; if you use PowerShell (specifically the more up to date PowerShell Core, not sure about the built in Windows PowerShell), it comes with a `cp` alias and can understand the `-r` flag just fine from what I can remember, so it should work fine here.

I 100% Agree with your point, I have added it to maintain the repo for "**Cross-Platform Consistency**"
For users who may not be familiar with PowerShell, using a dedicated library can provide a more straightforward API or command-line interface.

I can remove the change of copyfiles, Is the next js upgrade good with you?

**Comment by Ovyerus** [comment]
Yeah the Next.js upgrade is fine.

If copying does turn out to be a bigger issue, a simpler script using [fs.cp](https://nodejs.org/docs/latest/api/fs.html#fscpsrc-dest-options-callback) can probably be devised.

**Comment by codewithshinde** [comment]
> Yeah the Next.js upgrade is fine.
> 
> If copying does turn out to be a bigger issue, a simpler script using [fs.cp](https://nodejs.org/docs/latest/api/fs.html#fscpsrc-dest-options-callback) can probably be devised.

I have added a script file instead.

**Pull request merged**
